# This is a basic workflow to help you get started with Actions

name: Build Example Flutter Web

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build Example Web
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.commit_secret}}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version    
      - run: |
          cd example
          flutter config --enable-web
          flutter pub get
          flutter build web --release
          cd build/web
          git init
          # 改成你的提交邮箱
          git config --global user.email themorecolor@gmail.com
          # 改成你的提交用户名
          git config --global user.name wasabia
          git status
          
          git remote add origin https://${{secrets.commit_secret}}@github.com/wasabia/three_dart_example.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
